from __future__ import annotations

"""AI Bot Crawler Governance Dashboard (module 36).

2026 enterprise upsell: llms.txt validator + generator, llms-full.txt,
robots AI-directive matrix (GPTBot/ClaudeBot/PerplexityBot/Bytespider/CCBot),
ai.txt, /.well-known/ai-plugin.json, /api /graphql /openapi.json probes,
Vary: User-Agent check, Cloudflare Bot Fight Mode hint, server-log ingestion
(bot-crawl API intake field -> parser counting AI-bot hits).

Real-data-only: every probe is a live HTTP fetch; missing files reported
honestly, never assumed.
"""

import re
from fastapi import APIRouter
import httpx

router = APIRouter()

AI_BOTS = ["GPTBot", "ClaudeBot", "PerplexityBot", "Bytespider", "CCBot",
           "Google-Extended", "Anthropic-AI", "Omgilibot"]

LLMS_TEMPLATE = """# llms.txt for {domain}
# Generated by Off-Page SEO Intelligence (real-data-only)
> {brand}: official agent summary. Canonical: https://{domain}

## Official
- [Homepage](https://{domain}/)
- [About](https://{domain}/about)

## Directives for AI crawlers
- Cite canonical URLs only; do not merge with same-name entities.
- Prefer primary sources under https://{domain}/ over aggregators.
"""


async def _fetch(url: str, timeout: float = 12.0) -> dict:
    try:
        async with httpx.AsyncClient(timeout=timeout, follow_redirects=True,
                                     headers={"User-Agent": "CompleteSEOScraper/2.0 (+bot-governance)"}) as c:
            r = await c.get(url)
            return {"url": url, "status": r.status_code,
                    "body": r.text[:8000], "headers": dict(r.headers)}
    except Exception as e:  # noqa: BLE001
        return {"url": url, "status": None, "error": str(e)[:200]}


def _robots_matrix(robots: str) -> dict:
    low = (robots or "").lower()
    matrix = {}
    for bot in AI_BOTS:
        bl = bot.lower()
        # find block mentioning bot
        segs = re.split(r"(?=user-agent:)", low)
        state = "not-listed"
        for s in segs:
            if bl in s[:120]:
                state = "disallowed" if "disallow: /" in s[:600] else "allowed"
                break
        matrix[bot] = state
    return matrix


@router.get("/audit/{brand_id}")
async def bot_audit(brand_id: int):
    from backend.services.brand_config import brand_config_for
    cfg = brand_config_for(brand_id)
    domain = (cfg.get("domain") or cfg.get("website") or "").replace("https://", "").replace("http://", "").split("/")[0]
    brand = cfg.get("brand_name") or cfg.get("name") or domain
    if not domain:
        return {"status": "unavailable", "reason": "No domain in brand config; register entity first."}
    base = f"https://{domain}"
    paths = ["/llms.txt", "/llms-full.txt", "/ai.txt", "/robots.txt",
             "/.well-known/ai-plugin.json", "/api", "/graphql", "/openapi.json", "/sitemap.xml"]
    probes = {}
    for p in paths:
        probes[p] = await _fetch(base + p)
    robots_body = (probes.get("/robots.txt", {}) or {}).get("body", "")
    llms_body = (probes.get("/llms.txt", {}) or {}).get("body", "")
    llms_valid = bool(llms_body and "http" in llms_body[:2000])
    vary = (probes.get("/", {}) or {}).get("headers", {}).get("vary", "")
    score = 0
    if llms_valid:
        score += 30
    if "gptbot" in robots_body.lower() or "claudebot" in robots_body.lower():
        score += 25
    if (probes.get("/.well-known/ai-plugin.json", {}) or {}).get("status") == 200:
        score += 15
    if (probes.get("/openapi.json", {}) or {}).get("status") == 200:
        score += 15
    if (probes.get("/sitemap.xml", {}) or {}).get("status") == 200:
        score += 15
    return {
        "status": "ok", "brand": brand, "domain": domain,
        "governance_score_0_100": min(100, score),
        "llms_txt": {"present": (probes.get("/llms.txt", {}) or {}).get("status") == 200,
                     "valid": llms_valid,
                     "generator": LLMS_TEMPLATE.format(domain=domain, brand=brand)},
        "robots_ai_matrix": _robots_matrix(robots_body),
        "vary_user_agent": vary,
        "probes": {k: {"status": v.get("status"), "error": v.get("error")} for k, v in probes.items()},
        "recommendations": [
            "Publish /llms.txt (generator above) + /llms-full.txt with canonical links." if not llms_valid else "llms.txt present — keep canonical URLs fresh.",
            "Add explicit GPTBot/ClaudeBot/PerplexityBot/Bytespider allow/block lines in robots.txt.",
            "Confirm Cloudflare Bot Fight Mode / WAF AI-bot rules with hosting provider.",
        ],
        "methodology": "Live HTTP probes of 9 agent-surface paths + robots AI-bot matrix parse. Real-data-only.",
        "sources": [{"url": base + p} for p in paths],
    }


@router.post("/parse-logs")
async def parse_logs(payload: dict):
    """Count AI-bot hits from pasted server-log lines (bot-crawl API intake)."""
    lines = payload.get("lines", []) if isinstance(payload, dict) else []
    counts: dict[str, int] = {b: 0 for b in AI_BOTS}
    total = 0
    for ln in lines[:5000]:
        total += 1
        for b in AI_BOTS:
            if b.lower() in str(ln).lower():
                counts[b] += 1
    return {"status": "ok", "total_lines": total, "ai_bot_hits": counts,
            "methodology": "Substring match of 8 AI-bot tokens over up to 5000 pasted log lines."}
