from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import List, Optional
from pydantic import BaseModel
from datetime import datetime

from backend.core.database import get_db
from backend.models.models import Brand, EdgeRedirect, DeadEquitySalvage

router = APIRouter()


class EdgeRedirectCreate(BaseModel):
    brand_id: int
    source_url: str
    target_url: str
    redirect_type: str = "301"


@router.post("/redirects")
def create_redirect(redirect_data: EdgeRedirectCreate, db: Session = Depends(get_db)):
    brand = db.query(Brand).filter(Brand.id == redirect_data.brand_id).first()
    if not brand:
        raise HTTPException(status_code=404, detail="Brand not found")
    
    redirect = EdgeRedirect(**redirect_data.model_dump())
    db.add(redirect)
    db.commit()
    db.refresh(redirect)
    return redirect


@router.get("/redirects/{brand_id}")
def list_redirects(brand_id: int, db: Session = Depends(get_db)):
    return db.query(EdgeRedirect).filter(
        EdgeRedirect.brand_id == brand_id
    ).order_by(EdgeRedirect.created_at.desc()).all()


@router.post("/deploy/{redirect_id}")
def deploy_redirect(redirect_id: int, db: Session = Depends(get_db)):
    redirect = db.query(EdgeRedirect).filter(EdgeRedirect.id == redirect_id).first()
    if not redirect:
        raise HTTPException(status_code=404, detail="Redirect not found")
    
    cloudflare_worker = f"""
// Edge Redirect Worker - Auto-generated by Off-Page SEO Engine
addEventListener('fetch', event => {{
  event.respondWith(handleRequest(event.request))
}})

async function handleRequest(request) {{
  const url = new URL(request.url)
  
  if (url.pathname === '{redirect.source_url.replace("https://", "").split("/", 1)[-1] if "/" in redirect.source_url else "/"}') {{
    return Response.redirect('{redirect.target_url}', {redirect.redirect_type})
  }}
  
  return fetch(request)
}}
"""
    
    redirect.is_active = True
    redirect.deployed_at = datetime.utcnow()
    db.commit()
    
    return {
        "redirect_id": redirect.id,
        "status": "deployed",
        "worker_script": cloudflare_worker,
        "source": redirect.source_url,
        "target": redirect.target_url,
        "type": redirect.redirect_type
    }


@router.get("/dead-equity/{brand_id}")
def scan_dead_equity(brand_id: int, db: Session = Depends(get_db)):
    brand = db.query(Brand).filter(Brand.id == brand_id).first()
    if not brand:
        raise HTTPException(status_code=404, detail="Brand not found")
    
    dead_links = db.query(DeadEquitySalvage).filter(
        DeadEquitySalvage.brand_id == brand_id,
        DeadEquitySalvage.redirect_deployed == False
    ).all()
    
    total_equity = sum(d.equity_value or 0 for d in dead_links)
    
    return {
        "brand": brand.name,
        "dead_links_found": len(dead_links),
        "total_equity_at_risk": total_equity,
        "links": [
            {
                "source_url": d.source_url,
                "target_url": d.target_url,
                "http_status": d.http_status,
                "backlink_count": d.backlink_count,
                "domain_authority": d.domain_authority,
                "equity_value": d.equity_value
            } for d in dead_links
        ],
        "recommendation": "Deploy 301 redirects to recover lost link equity"
    }


@router.get("/edge-rules/{brand_id}")
def generate_edge_rules(brand_id: int, db: Session = Depends(get_db)):
    redirects = db.query(EdgeRedirect).filter(
        EdgeRedirect.brand_id == brand_id,
        EdgeRedirect.is_active == True
    ).all()
    
    rules = []
    for r in redirects:
        source_path = r.source_url.replace("https://", "").replace("http://", "")
        if "/" in source_path:
            source_path = "/" + source_path.split("/", 1)[1]
        
        rules.append({
            "pattern": source_path,
            "target": r.target_url,
            "status_code": int(r.redirect_type),
            "description": f"Redirect {r.source_url} to {r.target_url}"
        })
    
    cloudflare_config = {
        "type": "redirect_rules",
        "rules": [
            {
                "expression": f"http.request.uri.path eq \"{r['pattern']}\"",
                "action": "redirect",
                "target_url": r["target"],
                "status_code": r["status_code"]
            } for r in rules
        ]
    }
    
    return {
        "brand_id": brand_id,
        "active_rules": len(rules),
        "rules": rules,
        "cloudflare_config": cloudflare_config
    }
