from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from sqlalchemy import func
from typing import List, Optional
from pydantic import BaseModel
from datetime import datetime
import math

from backend.core.database import get_db
from backend.models.models import Brand, Backlink, ToxicBacklink, AnchorTextProfile

router = APIRouter()


@router.get("/scan/{brand_id}")
def scan_toxic_backlinks(brand_id: int, db: Session = Depends(get_db)):
    brand = db.query(Brand).filter(Brand.id == brand_id).first()
    if not brand:
        raise HTTPException(status_code=404, detail="Brand not found")
    
    backlinks = db.query(Backlink).filter(Backlink.brand_id == brand_id).all()
    
    toxic_indicators = []
    for bl in backlinks:
        toxicity_score = 0
        reasons = []
        
        if bl.domain_authority and bl.domain_authority < 20:
            toxicity_score += 30
            reasons.append("Low domain authority")
        
        if bl.is_toxic:
            toxicity_score += 50
            reasons.append("Previously flagged as toxic")
        
        if bl.anchor_text:
            commercial_anchors = ["buy", "cheap", "discount", "price", "sale"]
            if any(word in bl.anchor_text.lower() for word in commercial_anchors):
                toxicity_score += 20
                reasons.append("Commercial anchor text spam")
        
        if toxicity_score > 30:
            toxic_indicators.append({
                "source_url": bl.source_url,
                "source_domain": bl.source_domain,
                "toxicity_score": min(toxicity_score, 100),
                "reasons": reasons
            })
    
    return {
        "brand": brand.name,
        "total_backlinks_scanned": len(backlinks),
        "toxic_indicators_found": len(toxic_indicators),
        "toxic_backlinks": sorted(toxic_indicators, key=lambda x: x["toxicity_score"], reverse=True)[:50]
    }


@router.get("/anchor-entropy/{brand_id}")
def calculate_anchor_entropy(brand_id: int, db: Session = Depends(get_db)):
    backlinks = db.query(Backlink).filter(Backlink.brand_id == brand_id).all()
    
    anchor_counts = {}
    for bl in backlinks:
        anchor = bl.anchor_text or "(no anchor)"
        anchor_counts[anchor] = anchor_counts.get(anchor, 0) + 1
    
    total = len(backlinks)
    if total == 0:
        return {"message": "No backlinks found", "entropy": 0}
    
    entropy = 0
    for count in anchor_counts.values():
        prob = count / total
        if prob > 0:
            entropy -= prob * math.log2(prob)
    
    max_entropy = math.log2(len(anchor_counts)) if anchor_counts else 0
    normalized_entropy = entropy / max_entropy if max_entropy > 0 else 0
    
    over_optimization_risk = "low"
    if normalized_entropy < 0.3:
        over_optimization_risk = "high"
    elif normalized_entropy < 0.5:
        over_optimization_risk = "medium"
    
    anchor_profile = []
    for anchor, count in sorted(anchor_counts.items(), key=lambda x: x[1], reverse=True):
        percentage = count / total * 100
        anchor_profile.append({
            "anchor_text": anchor,
            "count": count,
            "percentage": round(percentage, 2),
            "is_risky": percentage > 30 and anchor != "(no anchor)"
        })
    
    return {
        "brand_id": brand_id,
        "total_backlinks": total,
        "unique_anchors": len(anchor_counts),
        "entropy_score": round(entropy, 4),
        "normalized_entropy": round(normalized_entropy, 4),
        "max_possible_entropy": round(max_entropy, 4),
        "over_optimization_risk": over_optimization_risk,
        "anchor_profile": anchor_profile[:20],
        "recommendation": "Diversify anchor text distribution" if over_optimization_risk != "low" else "Anchor distribution looks natural"
    }


@router.post("/disavow/{brand_id}")
def generate_disavow_file(brand_id: int, db: Session = Depends(get_db)):
    toxic = db.query(ToxicBacklink).filter(
        ToxicBacklink.brand_id == brand_id,
        ToxicBacklink.disavowed == False
    ).all()
    
    domains = set()
    urls = []
    for t in toxic:
        if t.is_pbn or (t.toxicity_score and t.toxicity_score > 70):
            domains.add(t.source_domain)
        else:
            urls.append(t.source_url)
    
    disavow_content = "# Disavow file generated by Off-Page SEO Engine\n"
    disavow_content += f"# Generated: {datetime.utcnow().isoformat()}\n"
    disavow_content += f"# Total entries: {len(domains) + len(urls)}\n\n"
    
    disavow_content += "# Domain-level disavows\n"
    for domain in sorted(domains):
        disavow_content += f"domain:{domain}\n"
    
    disavow_content += "\n# URL-level disavows\n"
    for url in sorted(urls):
        disavow_content += f"{url}\n"
    
    return {
        "brand_id": brand_id,
        "total_toxic_backlinks": len(toxic),
        "domains_to_disavow": len(domains),
        "urls_to_disavow": len(urls),
        "disavow_file": disavow_content,
        "instructions": "Upload this file to Google Search Console Disavow Tool"
    }


@router.get("/anomaly-detection/{brand_id}")
def detect_link_anomalies(brand_id: int, db: Session = Depends(get_db)):
    backlinks = db.query(Backlink).filter(
        Backlink.brand_id == brand_id
    ).order_by(Backlink.discovered_at.desc()).all()
    
    if len(backlinks) < 10:
        return {"message": "Insufficient data for anomaly detection", "backlinks_count": len(backlinks)}
    
    recent_30d = [b for b in backlinks if b.discovered_at and 
                  (datetime.utcnow() - b.discovered_at).days <= 30]
    previous_30d = [b for b in backlinks if b.discovered_at and 
                    30 < (datetime.utcnow() - b.discovered_at).days <= 60]
    
    velocity_change = 0
    if previous_30d:
        velocity_change = (len(recent_30d) - len(previous_30d)) / len(previous_30d) * 100
    
    anomalies = []
    if velocity_change > 200:
        anomalies.append({
            "type": "velocity_spike",
            "severity": "high",
            "description": f"Backlink velocity increased by {velocity_change:.1f}% in last 30 days",
            "recommendation": "Investigate source of sudden link growth"
        })
    
    recent_anchors = [b.anchor_text for b in recent_30d if b.anchor_text]
    commercial_count = sum(1 for a in recent_anchors if any(
        word in a.lower() for word in ["buy", "cheap", "price", "discount", "sale"]
    ))
    
    if recent_anchors and commercial_count / len(recent_anchors) > 0.3:
        anomalies.append({
            "type": "anchor_spam",
            "severity": "high",
            "description": f"{commercial_count}/{len(recent_anchors)} recent anchors are commercial keywords",
            "recommendation": "Possible automated link spam - review sources"
        })
    
    recent_domains = set(b.source_domain for b in recent_30d)
    if len(recent_30d) > 20 and len(recent_domains) < len(recent_30d) * 0.3:
        anomalies.append({
            "type": "pbn_pattern",
            "severity": "critical",
            "description": "Low domain diversity in recent backlinks - possible PBN network",
            "recommendation": "Audit link sources for private blog network footprints"
        })
    
    return {
        "brand_id": brand_id,
        "total_backlinks": len(backlinks),
        "recent_30d": len(recent_30d),
        "previous_30d": len(previous_30d),
        "velocity_change_pct": round(velocity_change, 2),
        "anomalies_detected": len(anomalies),
        "anomalies": anomalies,
        "risk_level": "critical" if any(a["severity"] == "critical" for a in anomalies) else
                     "high" if any(a["severity"] == "high" for a in anomalies) else "normal"
    }
